"""added notes to todo

Revision ID: 4810d2c094ad
Revises: bf133dffccec
Create Date: 2021-12-21 14:16:02.723325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4810d2c094ad'
down_revision = 'bf133dffccec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.add_column('todo', sa.Column('note_name', sa.String(length=100), nullable=True))
    op.add_column('todo', sa.Column('note_description', sa.String(length=1900), nullable=True))
    op.alter_column('todo', 'start',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'start',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150),
               nullable=False)
    op.drop_column('todo', 'note_description')
    op.drop_column('todo', 'note_name')
    op.create_table('notes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=900), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
