"""empty message

Revision ID: 5fb710763dd3
Revises: 720b3c197911
Create Date: 2022-02-09 14:25:15.896004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb710763dd3'
down_revision = '720b3c197911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labels', sa.Column('poster_labels_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'labels', 'users', ['poster_labels_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labels', type_='foreignkey')
    op.drop_column('labels', 'poster_labels_id')
    # ### end Alembic commands ###
