"""added forign key to notes

Revision ID: 720b3c197911
Revises: 4810d2c094ad
Create Date: 2021-12-21 14:40:11.902822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720b3c197911'
down_revision = '4810d2c094ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('poster_notes_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['poster_notes_id'], ['id'])
    op.drop_column('todo', 'note_name')
    op.drop_column('todo', 'note_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('note_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1900), nullable=True))
    op.add_column('todo', sa.Column('note_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'poster_notes_id')
    # ### end Alembic commands ###
