"""Initial Migration

Revision ID: bf133dffccec
Revises: 
Create Date: 2021-12-10 12:50:39.927880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf133dffccec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('todo', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('todo', 'start',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('todo', 'date',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('todo', 'day',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('todo', 'month',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('todo', 'year',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'year',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('todo', 'month',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('todo', 'day',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('todo', 'date',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('todo', 'start',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('todo', 'description',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.alter_column('todo', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
